services:
    _defaults:
        public: true
        bind:
          $elasticConfig: '%elastic%'

    App\Tests\Infrastructure\Share\Event\EventCollectorListener:
      public: true
      tags:
          - { name: broadway.domain.event_listener }

    events_to_elastic:
        class: App\Infrastructure\Share\Event\Consumer\SendEventsToElasticConsumer
        autowire: true

    events_repository:
        class: App\Infrastructure\Share\Event\Query\EventElasticRepository
        autowire: true

    App\Infrastructure\Share\Bus\CommandBus:
      public: true
      arguments:
        - '@messenger.bus.command'

    App\Infrastructure\Share\Bus\QueryBus:
      public: true
      arguments:
        - '@messenger.bus.query'

    _instanceof:

        App\Application\Command\CommandHandlerInterface:
          public: true
          tags:
            - { name: messenger.message_handler, bus: messenger.bus.command }

        App\Application\Query\QueryHandlerInterface:
          public: true
          tags:
            - { name: messenger.message_handler, bus: messenger.bus.query }
